services:
  certer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: certer
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:${PORT:-8080}" # REST API
      - "${CHALLENGE_PORT:-5002}:${CHALLENGE_PORT:-5002}" # HTTP-01 ACME Challenge Port
    volumes:
      # Mount configuration file
      - ./config.json:/config.json:ro
      # Persist issued SSL/TLS certificates and keys
      - ./certs:/certs
    env_file:
      - .env
    environment:
      # Point to the mounted configuration file
      - CONFIG_PATH=/config.json
      # Define certificate storage directory mapping to the mounted volume
      - CERT_STORAGE_DIR=/certs
