name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.x'
          cache: false

      - name: Download dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./...

      - name: Build Binaries
        run: make build

      - name: Import Secrets from Vault
        id: import-secrets
        uses: hashicorp/vault-action@v4
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          namespace: dev
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            cert-central/secret/data/registry username | REGISTRY_USERNAME ;
            cert-central/secret/data/registry password | REGISTRY_PASSWORD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.dmz.k8s.menscho.space
          username: ${{ steps.import-secrets.outputs.REGISTRY_USERNAME }}
          password: ${{ steps.import-secrets.outputs.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image (Multi-Platform)
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.dmz.k8s.menscho.space/m0space/cert-central:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
