package main

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"certer/internal/app/api"
	"certer/internal/app/config"
)

func TestFormatMarkdown(t *testing.T) {
	data := &AuditData{
		Teams: []config.TeamConfig{
			{ID: "system", Name: "System", Description: "System Team"},
			{ID: "team-1", Name: "Dev Team", Description: "Devs"},
		},
		CertConfigs: []config.CertConfig{
			{ID: "cert-1", Primary: "example.com", Sans: []string{"*.example.com"}, TeamID: "team-1", Description: "Test Cert", DNSProvider: "hetzner"},
		},
		APIKeys: []config.APIKeyConfig{
			{ID: "key-1", Description: "Key 1", AllowedCertificates: []string{"cert-1"}, AllowedTeams: []string{"team-1"}, Admin: false},
		},
		IssuedCerts: []api.CertificateStatusResponse{
			{ID: "cert-1", Domain: "example.com", Sans: []string{"*.example.com"}, Issued: true},
		},
	}

	markdown := formatMarkdown(data)

	// Check if key headers and tables exist
	if !strings.Contains(markdown, "# Certer System Audit Report") {
		t.Errorf("Expected Markdown to contain report title")
	}
	if !strings.Contains(markdown, "## 1. Teams") {
		t.Errorf("Expected Markdown to contain Teams section")
	}
	if !strings.Contains(markdown, "system | System | System Team") {
		t.Errorf("Expected Markdown to contain system team entry")
	}
	if !strings.Contains(markdown, "cert-1 | example.com | *.example.com | team-1 | Test Cert | hetzner | Yes") {
		t.Errorf("Expected Markdown to contain certificate configuration table entry with issuance status")
	}
	if !strings.Contains(markdown, "key-1 | Key 1 | No | team-1 | cert-1") {
		t.Errorf("Expected Markdown to contain API key table entry")
	}
}

func TestFormatHTML(t *testing.T) {
	daysRemaining := 45
	data := &AuditData{
		Teams: []config.TeamConfig{
			{ID: "team-1", Name: "Platform <Ops>", Description: "Owns edge & ingress"},
		},
		CertConfigs: []config.CertConfig{
			{ID: "cert-ok", Primary: "ok.example.com", Sans: []string{"www.ok.example.com"}, TeamID: "team-1", Description: "Primary <cert>", DNSProvider: "hetzner"},
			{ID: "cert-warning", Primary: "warning.example.com", TeamID: "team-1"},
			{ID: "cert-critical", Primary: "critical.example.com", TeamID: "team-1"},
			{ID: "cert-unissued", Primary: "unissued.example.com", TeamID: "team-1"},
		},
		APIKeys: []config.APIKeyConfig{
			{
				ID:                  "key-1",
				Token:               "$argon2id$v=19$m=65536,t=3,p=2$secret-hash",
				Description:         "Deploy key <blue>",
				AllowedTeams:        []string{"team-1"},
				AllowedCertificates: []string{"cert-ok"},
				Admin:               false,
			},
		},
		IssuedCerts: []api.CertificateStatusResponse{
			{ID: "cert-ok", Domain: "ok.example.com", Issued: true, Status: "ok", ExpiresAt: "2026-10-01T00:00:00Z", DaysRemaining: &daysRemaining, IsValid: true},
			{ID: "cert-warning", Domain: "warning.example.com", Issued: true, Status: "warning", Reason: "certificate is expiring soon"},
			{ID: "cert-critical", Domain: "critical.example.com", Issued: true, Status: "critical", Reason: "certificate has expired"},
			{ID: "cert-unissued", Domain: "unissued.example.com", Issued: false, Status: "critical", Reason: "certificate file missing or unreadable"},
		},
	}

	html, err := formatHTML(data, ReportMeta{
		GeneratedAt: time.Date(2026, 7, 10, 12, 30, 0, 0, time.UTC),
		TargetURL:   "http://localhost:8080",
	})
	if err != nil {
		t.Fatalf("formatHTML failed: %v", err)
	}

	expected := []string{
		"<!doctype html>",
		"Certer System Report",
		"generated by certer audit",
		"Certificates",
		"Teams",
		"API Keys",
		"Total Certificates",
		">4<",
		"status-ok",
		"status-warning",
		"status-critical",
		"ok.example.com",
		"45 days",
		"Platform &lt;Ops&gt;",
		"Deploy key &lt;blue&gt;",
	}
	for _, want := range expected {
		if !strings.Contains(html, want) {
			t.Errorf("Expected HTML to contain %q", want)
		}
	}

	for _, forbidden := range []string{"$argon2id$", "secret-hash", "private_key", "BEGIN CERTIFICATE", "BEGIN PRIVATE KEY"} {
		if strings.Contains(html, forbidden) {
			t.Errorf("HTML contained forbidden sensitive value %q", forbidden)
		}
	}
	if strings.Contains(html, "Platform <Ops>") || strings.Contains(html, "Deploy key <blue>") {
		t.Error("Expected HTML renderer to escape user-controlled text")
	}
}

func TestFormatJSON(t *testing.T) {
	data := &AuditData{
		Teams: []config.TeamConfig{
			{ID: "team-1", Name: "Dev Team"},
		},
	}

	jsonData, err := formatJSON(data)
	if err != nil {
		t.Fatalf("formatJSON failed: %v", err)
	}

	var parsed AuditData
	if err := json.Unmarshal([]byte(jsonData), &parsed); err != nil {
		t.Fatalf("Failed to parse JSON output: %v", err)
	}

	if len(parsed.Teams) != 1 || parsed.Teams[0].Name != "Dev Team" {
		t.Errorf("Expected team 'Dev Team' inside parsed JSON, got: %+v", parsed.Teams)
	}
}

func TestFetchAuditData(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		auth := r.Header.Get("Authorization")
		if auth != "Bearer test-admin-token" {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
		w.Header().Set("Content-Type", "application/json")

		switch r.URL.Path {
		case "/api/v1/config/teams":
			_ = json.NewEncoder(w).Encode([]config.TeamConfig{{ID: "team-1", Name: "Team 1"}})
		case "/api/v1/config/certificates":
			_ = json.NewEncoder(w).Encode([]config.CertConfig{{ID: "cert-1", Primary: "example.com"}})
		case "/api/v1/config/api_keys":
			_ = json.NewEncoder(w).Encode([]config.APIKeyConfig{{ID: "key-1", Description: "Key 1"}})
		case "/api/v1/certificates/status":
			_ = json.NewEncoder(w).Encode([]api.CertificateStatusResponse{{ID: "cert-1", Domain: "example.com", Issued: true}})
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer ts.Close()

	ctx := context.Background()
	client := &http.Client{}

	t.Run("Success", func(t *testing.T) {
		data, err := fetchAuditData(ctx, client, ts.URL, "test-admin-token")
		if err != nil {
			t.Fatalf("fetchAuditData failed: %v", err)
		}

		if len(data.Teams) != 1 || data.Teams[0].ID != "team-1" {
			t.Errorf("Unexpected teams output: %+v", data.Teams)
		}
		if len(data.CertConfigs) != 1 || data.CertConfigs[0].ID != "cert-1" {
			t.Errorf("Unexpected cert configs output: %+v", data.CertConfigs)
		}
		if len(data.APIKeys) != 1 || data.APIKeys[0].ID != "key-1" {
			t.Errorf("Unexpected api keys output: %+v", data.APIKeys)
		}
		if len(data.IssuedCerts) != 1 || data.IssuedCerts[0].ID != "cert-1" || !data.IssuedCerts[0].Issued {
			t.Errorf("Unexpected issued certs output: %+v", data.IssuedCerts)
		}
	})

	t.Run("Unauthorized", func(t *testing.T) {
		_, err := fetchAuditData(ctx, client, ts.URL, "bad-token")
		if err == nil {
			t.Fatal("Expected fetch to fail on unauthorized status, but succeeded")
		}
	})
}

func TestRunAuditHTMLFormatAndOutput(t *testing.T) {
	ts := newAuditTestServer(t)
	outputPath := filepath.Join(t.TempDir(), "certer-report.html")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := runAudit([]string{
		"-token", "test-admin-token",
		"-url", ts.URL,
		"-format", "html",
		"-output", outputPath,
	}, &stdout, &stderr, emptyEnv)

	if code != 0 {
		t.Fatalf("Expected exit code 0, got %d; stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("Expected stdout to stay empty when -output is used, got %q", stdout.String())
	}

	reportBytes, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Expected output file to be written: %v", err)
	}
	report := string(reportBytes)
	if !strings.Contains(report, "Certer System Report") || !strings.Contains(report, "cert-1") {
		t.Fatalf("Output file did not contain expected HTML report: %s", report)
	}
}

func TestRunAuditHTMLFormatFromEnv(t *testing.T) {
	ts := newAuditTestServer(t)

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := runAudit([]string{
		"-token", "test-admin-token",
		"-url", ts.URL,
	}, &stdout, &stderr, mapEnv(map[string]string{"AUDIT_FORMAT": "html"}))

	if code != 0 {
		t.Fatalf("Expected exit code 0, got %d; stderr=%s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "Certer System Report") {
		t.Fatalf("Expected stdout to contain HTML report, got %q", stdout.String())
	}
}

func TestRunAuditSampleHTMLDoesNotRequireToken(t *testing.T) {
	outputPath := filepath.Join(t.TempDir(), "sample-report.html")

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := runAudit([]string{
		"-sample",
		"-format", "html",
		"-output", outputPath,
	}, &stdout, &stderr, emptyEnv)

	if code != 0 {
		t.Fatalf("Expected exit code 0, got %d; stderr=%s", code, stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("Expected stdout to stay empty when -output is used, got %q", stdout.String())
	}

	reportBytes, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Expected sample output file to be written: %v", err)
	}
	report := string(reportBytes)
	for _, want := range []string{"Certer System Report", "app.example.com", "payments.example.com", "status-warning", "status-critical"} {
		if !strings.Contains(report, want) {
			t.Fatalf("Expected sample report to contain %q, got %s", want, report)
		}
	}
}

func TestRunAuditSampleFromEnv(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := runAudit([]string{
		"-format", "html",
	}, &stdout, &stderr, mapEnv(map[string]string{"AUDIT_SAMPLE": "true"}))

	if code != 0 {
		t.Fatalf("Expected exit code 0, got %d; stderr=%s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "app.example.com") {
		t.Fatalf("Expected stdout to contain sample HTML report, got %q", stdout.String())
	}
}

func TestRunAuditRejectsUnknownFormat(t *testing.T) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := runAudit([]string{
		"-token", "test-admin-token",
		"-format", "xml",
	}, &stdout, &stderr, emptyEnv)

	if code == 0 {
		t.Fatal("Expected non-zero exit code for unknown format")
	}
	if !strings.Contains(stderr.String(), "unsupported output format") {
		t.Fatalf("Expected unsupported format error, got %q", stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("Expected stdout to stay empty, got %q", stdout.String())
	}
}

func TestNormalizeURL(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"", ""},
		{"http://localhost:8080", "http://localhost:8080"},
		{"https://certer.menscho.space/", "https://certer.menscho.space"},
		{"certer.menscho.space", "http://certer.menscho.space"},
		{"certer.menscho.space/", "http://certer.menscho.space"},
		{"http://127.0.0.1/", "http://127.0.0.1"},
	}

	for _, tc := range tests {
		got := normalizeURL(tc.input)
		if got != tc.expected {
			t.Errorf("normalizeURL(%q) = %q; expected %q", tc.input, got, tc.expected)
		}
	}
}

func newAuditTestServer(t *testing.T) *httptest.Server {
	t.Helper()

	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		auth := r.Header.Get("Authorization")
		if auth != "Bearer test-admin-token" {
			w.WriteHeader(http.StatusUnauthorized)
			return
		}
		w.Header().Set("Content-Type", "application/json")

		switch r.URL.Path {
		case "/api/v1/config/teams":
			_ = json.NewEncoder(w).Encode([]config.TeamConfig{{ID: "team-1", Name: "Team 1"}})
		case "/api/v1/config/certificates":
			_ = json.NewEncoder(w).Encode([]config.CertConfig{{ID: "cert-1", Primary: "example.com", TeamID: "team-1"}})
		case "/api/v1/config/api_keys":
			_ = json.NewEncoder(w).Encode([]config.APIKeyConfig{{ID: "key-1", Token: "$argon2id$hash", Description: "Key 1"}})
		case "/api/v1/certificates/status":
			daysRemaining := 20
			_ = json.NewEncoder(w).Encode([]api.CertificateStatusResponse{{ID: "cert-1", Domain: "example.com", Issued: true, Status: "warning", DaysRemaining: &daysRemaining}})
		default:
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	t.Cleanup(ts.Close)
	return ts
}

func emptyEnv(string) string {
	return ""
}

func mapEnv(values map[string]string) func(string) string {
	return func(key string) string {
		return values[key]
	}
}
